import "@/styles/tip.css";
import TipItem from "@/components/tipItem";

export const metadata = {
    title: "BSirWays :: Tips",
    description: "Generated by create next app", 
};


export default function Tips() {
    return (
        <div className="holder">
            <div className="section-header">
                <h2>Tips para viajar de forma Sustentable</h2>
                <p>Pequeñas acciones que hacen una gran diferencia.</p>
            </div>

            <div className="tips-grid">
                <TipItem />
                
            </div>
        </div>
    )
}
