import "@/styles/globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "BSirWays",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        
        {children}
      
        <footer>
          <p>Diseñado por Martina Lopardo - &copy;2026</p>
        </footer>
      </body>
    </html>
  );
}
