import "@/styles/globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "BSirWays",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
      </head>
      <body>

        <Nav />

        {children}

        <footer>
          <p>Diseñado por Martina Lopardo - &copy;2026</p>
        </footer>
      </body>
    </html>
  );
}
