import "@/styles/globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "BSirWays",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="container nav-content holder">
            <div className="logo">BAirWays</div>
          </div>
        </header>
        <Nav />
        
        {children}
      
        <footer>
          <p>Diseñado por Martina Lopardo - &copy;2025</p>
        </footer>
      </body>
    </html>
  );
}
