"use client";

import "@/styles/tip.css";
import TipItem from "@/components/tipItem";
import { useEffect, useState } from "react";

//Como uso use client esto no va
/*export const metadata = {
    title: "BSirWays :: Tips",
    description: "Generated by create next app", 
};*/

export default function Tips() {

  //traigo los tips desde el backend
  const [tips, setTips] = useState([]);
  useEffect(() => {
    fetch("http://localhost:3001/api/tips")
      .then(res => res.json())
      .then(data => {
        console.log("DATA FRONT:", data);
        setTips(data);
      })
      .catch(error => console.error("Error:", error));
  }, []);


  return (
    <section className="tips">
      <div className="holder">
        <div className="section-header">
          <h2>Tips para viajar de forma Sustentable</h2>
          <p>Pequeñas acciones que hacen una gran diferencia.</p>
        </div>

        <div className="tips-grid">
          {tips.map((tip) => (
            <TipItem
              key={tip.id}
              titulo={tip.titulo}
              subtitulo={tip.subtitulo}
              descripcion={tip.descripcion}
              icono_clase={tip.icono_clase}
            />
          ))}
        </div>
      </div>
    </section>
  )
}
