import "@/styles/tip.css";
import DestinoItem from "@/components/destinoItem";

export const metadata = {
    title: "BSirWays :: Destinos",
    description: "Generated by create next app", 
};


export default function Destinos() {
    return (
            <div className="container holder">
                <div className="section-header">
                    <h2>Lugares para visitar</h2>
                    <p>Descubre museos, parques, puntos históricos y culturales de Buenos Aires</p>
                </div>

                <div className="ba-grid">
                    <DestinoItem />
                </div>
            </div>
        )
    }