"use client";

import "@/styles/destino.css";
import DestinoItem from "@/components/destinoItem";
import { useEffect, useState } from "react";


// como uso use client esto no va
/*export const metadata = {
    title: "BSirWays :: Destinos",
    description: "Generated by create next app", 
};*/


export default function Destinos() {

  // para traer los destinos desde el backend
  const [destinosBA, setDestinosBA] = useState([]);
  useEffect(() => {
    fetch("http://localhost:3001/api/destinos")
      .then(res => res.json())
      .then(data => {
        console.log("DATA FRONT:", data);
        setDestinosBA(data);
      })
      .catch(error => console.error("Error:", error));
  }, []);

  return (
    <section id="destinos" className="buenos-aires">
      <div className="container holder">
        <div className="section-header">
          <h2>Lugares para visitar</h2>
          <p>Descubre museos, parques, puntos históricos y culturales de Buenos Aires</p>
        </div>

        <div className="ba-grid">
          {destinosBA.map((destino) => (
            <DestinoItem
              key={destino.id}
              id={destino.id}
              nombre={destino.nombre}
              texto={destino.descripcion}
              imagen={`/img/${destino.imagen}`}
              tipo_destino={destino.tipo_destino}
              tiempo={destino.tiempo}
              precio={destino.precio}
            />
          ))}
        </div>
      </div>
    </section>
  )
}

